# Generated by Django 3.2.5 on 2023-09-15 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserIngredient',
            new_name='RecipieIngredient',
        ),
    ]
