# Generated by Django 3.2.5 on 2023-09-18 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_rename_useringredient_recipieingredient'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipieIngredient',
            new_name='RecipeIngredient',
        ),
    ]
